paths:
  /api/v1/auth/login:
    post:
      summary: Login API for app
      tags:
        - Login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
            example:
              email: "reza@gmail.com"
              password: "password"

      responses:
        200:
          description: "- Success"
        400:
          summary: "Bad Request"
          description: "- Email field was empty!\n- Password field was empty!\n Password was wrong!"
        404:
          summary: "Not Found"
          description: "- User not found!"
