version: '3.5'
services:

  # ------------------------------ dev database ------------------------------ #
  dev-db:
    # for linux
    image: postgres:14.1-alpine 
    # --------
    # for windows
    # image: postgres:14.1
    # --------
    restart: always
    container_name: postgres-todo
    networks:
      - todo-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5434:5432

  # ------------------------------ test database ----------------------------- #
  test-db:
    # for linux
    image: postgres:14.1-alpine 
    # --------
    # for windows
    # image: postgres:14.1
    # --------
    container_name: postgres-test-todo
    networks:
      - todo-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-test
    ports:
      - 5435:5432

  # --------------------------------- backend -------------------------------- #
  todo:
    container_name: todo
    image: todo
    build:
      context: ./
      target: debug
    restart: always
    command: npm run start:dev
    env_file:
      - ./.env
    networks:
      - todo-service
    volumes:
      - ./:/todo-service
    ports:
      - 3001:3001
  # --------------------------------- Swagger -------------------------------- #
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./src/api/v1/doc/swagger/:/usr/share/nginx/html/doc
    links:
      - todo
    environment:
      API_URL: doc/swagger/authmanagement.yaml
      # URLS: "[
      #   { url: \"./authmanagement.yml\", name: \"authManagment\" },
      #   ]"

networks:
  todo-service:


volumes:
  db:
